const root=document.documentElement,modal=document.querySelector('#modal'),cursor=document.querySelector('.cursor');
document.querySelectorAll('.form-open').forEach(button=>button.addEventListener('click',()=>modal.showModal()));
document.querySelector('.close').addEventListener('click',()=>modal.close());modal.addEventListener('click',event=>{if(event.target===modal)modal.close()});
document.querySelector('#form').addEventListener('submit',event=>{event.preventDefault();event.currentTarget.innerHTML='<p style="font:600 28px/1.05 Syne,sans-serif">Есть. В реальном проекте заявка уйдёт тренеру.</p>'});
const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('in')),{threshold:.14});document.querySelectorAll('.reveal').forEach(item=>reveal.observe(item));
document.querySelectorAll('.path-card').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.path-card').forEach(item=>item.classList.remove('active'));card.classList.add('active');root.style.setProperty('--accent',`var(--${card.dataset.tone})`);document.querySelector('#path-caption').textContent=card.dataset.copy}));
const image=document.querySelector('[data-tilt]');image.addEventListener('pointermove',event=>{const box=image.getBoundingClientRect(),x=(event.clientX-box.left)/box.width-.5,y=(event.clientY-box.top)/box.height-.5;image.style.transform=`perspective(800px) rotateY(${x*5}deg) rotateX(${y*-5}deg) translate(${x*6}px,${y*6}px)`});image.addEventListener('pointerleave',()=>image.style.transform='');
if(matchMedia('(pointer:fine)').matches){window.addEventListener('pointermove',event=>{cursor.style.left=event.clientX+'px';cursor.style.top=event.clientY+'px'});document.querySelectorAll('a,button,.dial').forEach(item=>{item.addEventListener('pointerenter',()=>cursor.classList.add('big'));item.addEventListener('pointerleave',()=>cursor.classList.remove('big'))})}
const dial=document.querySelector('#dial'),value=document.querySelector('#dial-value'),rounds=document.querySelector('#dial-rounds'),label=document.querySelector('#dial-label'),mark=dial.querySelector('.dial-mark');let minutes=45;
function renderDial(){const pct=(minutes-30)/45,deg=130+pct*190;dial.style.background=`conic-gradient(var(--accent) 0deg,var(--accent) ${deg}deg,#c8c2b6 ${deg}deg)`;mark.style.transform=`translateX(-50%) rotate(${deg-180}deg)`;value.textContent=minutes;rounds.textContent=`0${Math.round(minutes/15)} РАУНДА`;label.textContent=minutes<46?'ТЕХНИКА + ТЕМП':minutes<61?'СИЛА + ВЫНОСЛИВОСТЬ':'ПОЛНЫЙ ФАЙТ-КЭМП'}
function setDial(event){const rect=dial.getBoundingClientRect(),angle=(Math.atan2(event.clientY-rect.top-rect.height/2,event.clientX-rect.left-rect.width/2)*180/Math.PI+450)%360;minutes=Math.round((30+Math.max(0,Math.min(1,(angle-130+360)%360/190))*45)/5)*5;renderDial()}let dragging=false;dial.addEventListener('pointerdown',event=>{dragging=true;dial.setPointerCapture(event.pointerId);setDial(event)});dial.addEventListener('pointermove',event=>dragging&&setDial(event));dial.addEventListener('pointerup',()=>dragging=false);dial.addEventListener('keydown',event=>{if(['ArrowRight','ArrowUp'].includes(event.key))minutes=Math.min(75,minutes+5);if(['ArrowLeft','ArrowDown'].includes(event.key))minutes=Math.max(30,minutes-5);renderDial()});renderDial();
